package com.numplates.nomera3.presentation.router;

/**
 * created by c7j on 31.10.18
 */
public interface IActionContainer {

    String ACTION_START_CALL = "ACTION_START_CALL";
    String ACTION_OPEN_CHAT = "ACTION_OPEN_CHAT";
    String ACTION_FRIEND_REQUEST = "ACTION_FRIEND_REQUEST";
    String ACTION_FRIEND_CONFIRM = "ACTION_FRIEND_CONFIRM";
    String ACTION_OPEN_GIFTS = "ACTION_OPEN_GIFTS";
    String ACTION_LEAVE_POST_COMMENTS = "ACTION_LEAVE_POST_COMMENTS";
    String ACTION_LEAVE_POST_COMMENT_REACTIONS = "ACTION_LEAVE_POST_COMMENT_REACTIONS";
    String ACTION_REPLY_POST_COMMENTS = "ACTION_REPLY_POST_COMMENTS";
    String ACTION_ADD_TO_GROUP_CHAT = "ACTION_ADD_TO_GROUP_CHATß";
    String ACTION_REQUEST_TO_GROUP = "ACTION_REQUEST_TO_GROUP";
    String ACTION_OPEN_APP = "ACTION_OPEN_APP";
    String ACTION_OPEN_MOMENT = "ACTION_OPEN_MOMENT";
    String ACTION_OPEN_MAP = "ACTION_OPEN_MAP";
    String ACTION_OPEN_POST = "ACTION_OPEN_POST";
    String ACTION_OPEN_POST_WITH_REACTIONS = "ACTION_OPEN_POST_WITH_REACTIONS";
    String ACTION_OPEN_GALLERY_WITH_REACTIONS = "ACTION_OPEN_GALLERY_WITH_REACTIONS";
    String ACTION_OPEN_PEOPLE = "ACTION_OPEN_PEOPLE";
    String ACTION_SYSTEM_EVENT = "ACTION_SYSTEM_EVENT";
    String ACTION_OPEN_AUTHORIZATION = "ACTION_OPEN_AUTHORIZATION";

    String ACTION_OPEN_EVENT = "ACTION_OPEN_EVENT";// открыть вкладку уведомления
    String ACTION_OPEN_OWN_PROFILE = "ACTION_OPEN_OWN_PROFILE";// открыть свой профиль
    String ACTION_OPEN_OWN_CHAT_LIST = "ACTION_OPEN_OWN_CHAT_LIST";// открыть списки диалогов
    String ACTION_OPEN_REFERAL = "ACTION_OPEN_REFERAL"; // открыть реферальный экран
    String ACTION_OPEN_BIRTHDAY_GIFTS = "ACTION_OPEN_BIRTHDAY_GIFTS"; // открыть экран подарков в профиле именинника
    String ACTION_OPEN_BIRTHDAY_GROUP = "ACTION_OPEN_BIRTHDAY_GROUP"; // открыть группу уведомлений, связанных с днем рождения
    String ACTION_OPEN_SELF_BIRTHDAY = "ACTION_OPEN_SELF_BIRTHDAY";
    String ACTION_OPEN_EVENT_ON_MAP = "ACTION_OPEN_EVENT_ON_MAP";

    String ACTION_CALL_UNAVAILABLE = "ACTION_EVENT_CALL_UNAVAILABLE";
}
